### ISSUE TITLE
Turn nested fields off, does not allow lucene query on 5.5.3.

### ISSUE THREAD

**Issue by warren-li** [ppadovani/KibanaNestedSupportPlugin#50]
After install the knql plugin, with the nested fields turn off for the index, the lucene query still using the knql plugin. Is there a way to toggle to use lucene query and KNQL query depend on the activation of the nested object for an index?

**Comment by ppadovani** [comment]
I've confirmed an odd behavior with the search bar related to what you have reported. It looks like there are two issues that I did not notice before:

1. The text in the search bar is not properly indicating the query language KNQL/Lucene
2. When nested support is turned off, the query bar always seems to reset the query to * even if a properly formatted lucene query is entered.

I will look at this over the next few days. I would expect a fix to be published this weekend due to work and real life getting in the way.

**Comment by ppadovani** [comment]
fixed and released 5.5.3-1.0.4
