### ISSUE TITLE
Support Nested object without requiring KNQL - Query Language

### ISSUE THREAD

**Issue by pavolloffay** [ppadovani/KibanaNestedSupportPlugin#86]
Did you consider supporting nested objects without changing query language? 

e.g. `foo.nested:"abc" rather then current language `foo.nested="abc"`?

**Comment by ppadovani** [comment]
Yes... this would require that I write a parser that could handle that specific query language. I had some very specific reasons for going down a SQL like path:

- Easier for most to understand, as most may have seen SQL like languages before
- The need to be able to scope different nested query expressions in order to isolate query behavior. This caused the creation of the EXISTS keyword in my language.
- There are one or two language artifacts in the native Elasticsearch query language that would have made writing a parser impossible. To be clear, what my parser does under the covers is generate a native elastic search JSON query. The built-in query language used in Kibana is just passed to elastic search directly.
